name: Smuggler2

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: ${{matrix.ghc }}-${{ matrix.os }}, ${{ matrix.cabal }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ghc: [latest, '8.8.3']
        cabal: ['3.2']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        experimental: [false]
        include:
          - ghc: '8.6.5'
            cabal: latest
            os: ubuntu-latest
            experimental: true

    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}


      - uses: actions/cache@v2
        name: Cache cabal-store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-cabal-${{ matrix.ghc-version }}-cabal

      - name: Versions
        run: |
          cabal --version
          ghc --version
          cabal gen-bounds

      - name: Build
        run: |
          cabal update
          cabal clean
          cabal build all --enable-tests --write-ghc-environment-files=always

      - name: Test
        run: |
          # -j1 because tests fail in Windows otherwise
          cabal test --test-option=--delete-output=onpass --test-option=-j1
